# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: SN7k.LiteBright
PackageVersion: 1.2.0
MinimumOSVersion: 10.0.0.0
InstallerType: inno
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-04
Installers:
  - Architecture: x64
    Scope: user
    InstallerUrl: https://github.com/SN7k/LiteBright/releases/download/v1.2.0/LiteBright-Setup-1.2.0.exe
    InstallerSha256: 44F57C25F351E9CB94CE1503626DF2D14C0BDD424F768276DB9B3D9BC39B4734
    ProductCode: '{A7B3C2D1-E4F5-4A6B-8C9D-0E1F2A3B4C5D}_is1'
ManifestType: installer
ManifestVersion: 1.9.0
